version: '3'

services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: website-dimensioning-solar
    container_name: nodejs
    #user: "node:node"
    environment:
      - APP_PORT=${APP_PORT:-3000}
    volumes:
      - ".:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    